TREMO_SDK_PATH ?= $(CURDIR)
PROJECT_DIR := $(TREMO_SDK_PATH)/projects/ASR6601CB-EVAL/examples/ra08_uart_modem
TOOLCHAIN_PATH ?= $(TREMO_SDK_PATH)/tools/toolchain/bin/
SERIAL_PORT ?= COM20
SERIAL_BAUDRATE ?= 921600

.PHONY: all clean flash test

all:
	$(MAKE) -C $(PROJECT_DIR) TREMO_SDK_PATH=$(TREMO_SDK_PATH) TOOLCHAIN_PATH=$(TOOLCHAIN_PATH)

clean:
	$(MAKE) -C $(PROJECT_DIR) TREMO_SDK_PATH=$(TREMO_SDK_PATH) TOOLCHAIN_PATH=$(TOOLCHAIN_PATH) clean

flash:
	$(MAKE) -C $(PROJECT_DIR) TREMO_SDK_PATH=$(TREMO_SDK_PATH) TOOLCHAIN_PATH=$(TOOLCHAIN_PATH) SERIAL_PORT=$(SERIAL_PORT) SERIAL_BAUDRATE=$(SERIAL_BAUDRATE) flash

test:
	python tools/tests/ra08_regression.py
